// ─── SESSIONS (للعرض العام) ───────────────────────────────────────────────────
export const SESSIONS = [
    {
        _id: 's1',
        type: 'تطوير ذاتي',
        title: 'بناء الثقة بالنفس وتطوير مهارات القيادة',
        format: 'online',
        durationHours: 1, durationMinutes: 30,
        availableSeats: 12,
        price: 0,
        rating: 4.9, reviews: 124,
        image: 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=600',
        coachId: { _id: 'co2', fullName: 'أمينة بوعلام' },
    },
    {
        _id: 's2',
        type: 'تسويق رقمي',
        title: 'استراتيجيات التسويق الرقمي للمشاريع الصغيرة',
        format: 'online',
        durationHours: 2, durationMinutes: 0,
        availableSeats: 8,
        price: 3500,
        rating: 4.7, reviews: 89,
        image: 'https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg?auto=compress&cs=tinysrgb&w=600',
        coachId: { _id: 'co1', fullName: 'كريم مساعدية' },
    },
    {
        _id: 's3',
        type: 'ريادة أعمال',
        title: 'إطلاق مشروعك من الصفر: من الفكرة إلى الربح',
        format: 'in-person',
        location: 'الجزائر العاصمة',
        durationHours: 3, durationMinutes: 0,
        availableSeats: 0,
        price: 8000,
        rating: 5.0, reviews: 47,
        image: 'https://images.pexels.com/photos/1181396/pexels-photo-1181396.jpeg?auto=compress&cs=tinysrgb&w=600',
        coachId: { _id: 'co1', fullName: 'كريم مساعدية' },
    },
    {
        _id: 's4',
        type: 'موارد بشرية',
        title: 'تقنيات المقابلة الوظيفية واختيار الكفاءات',
        format: 'online',
        durationHours: 1, durationMinutes: 45,
        availableSeats: 5,
        price: 5500,
        rating: 4.6, reviews: 63,
        image: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=600',
        coachId: { _id: 'co4', fullName: 'سارة بن عمر' },
    },
];

// ─── COURSES (للعرض العام) ────────────────────────────────────────────────────
export const COURSES = [
    {
        _id: 'c1',
        title: 'أساسيات التفكير النقدي وحل المشكلات',
        category: 'تطوير ذاتي',
        level: 'مبتدئ',
        coachName: 'د. أمينة بوعلام',
        modules: Array(12).fill(null),
        price: 0,
        hasCertificate: true,
        image: 'https://images.pexels.com/photos/1181396/pexels-photo-1181396.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        _id: 'c2',
        title: 'إتقان التسويق عبر مواقع التواصل الاجتماعي',
        category: 'تسويق',
        level: 'متوسط',
        coachName: 'كريم مساعدية',
        modules: Array(8).fill(null),
        price: 12000,
        hasCertificate: true,
        image: 'https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        _id: 'c3',
        title: 'تطوير تطبيقات الجوال باستخدام React Native',
        category: 'برمجة',
        level: 'متقدم',
        coachName: 'ياسين تيزي',
        modules: Array(20).fill(null),
        price: 25000,
        hasCertificate: false,
        image: 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        _id: 'c4',
        title: 'التخطيط المالي الشخصي والاستثمار الذكي',
        category: 'مالية',
        level: 'مبتدئ',
        coachName: 'سارة بن عمر',
        modules: Array(10).fill(null),
        price: 9500,
        hasCertificate: true,
        image: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
];

// ─── COACHES ──────────────────────────────────────────────────────────────────
export const COACHES = [
    {
        _id: 'co1',
        userId: 'u1',
        fullName: 'كريم مساعدية',
        coachingName: 'كريم مساعدية',
        specialty: 'تسويق رقمي وريادة أعمال',
        location: 'الجزائر العاصمة',
        experience: 8,
        rating: 4.9,
        reviews: 234,
        isVerified: true,
        avatarColor: 'from-amber-500 to-yellow-500',
    },
    {
        _id: 'co2',
        userId: 'u2',
        fullName: 'أمينة بوعلام',
        coachingName: 'أمينة بوعلام',
        specialty: 'تطوير الذات والقيادة',
        location: 'وهران',
        experience: 12,
        rating: 5.0,
        reviews: 189,
        isVerified: true,
        avatarColor: 'from-violet-600 to-purple-400',
    },
    {
        _id: 'co3',
        userId: 'u3',
        fullName: 'ياسين تيزي',
        coachingName: 'ياسين تيزي',
        specialty: 'برمجة وتكنولوجيا',
        location: null,
        experience: 6,
        rating: 4.8,
        reviews: 156,
        isVerified: true,
        avatarColor: 'from-teal-600 to-emerald-400',
    },
    {
        _id: 'co4',
        userId: 'u4',
        fullName: 'سارة بن عمر',
        coachingName: 'سارة بن عمر',
        specialty: 'تخطيط مالي واستثمار',
        location: 'قسنطينة',
        experience: 10,
        rating: 4.7,
        reviews: 98,
        isVerified: true,
        avatarColor: 'from-pink-600 to-rose-400',
    },
];

// ─── BOOKINGS ─────────────────────────────────────────────────────────────────
// Format unifié utilisé par CoachBookings ET CoachDashboard (CalendarSection)
// Champs requis :
//   CoachBookings  → _id, name, category, status, date, time, participants,
//                    rawParticipants, capacity, unitPrice, totalPrice
//   CoachDashboard → category, date, time, name, participants, rawParticipants,
//                    capacity, enrolledStudents, totalPrice
export const BOOKINGS = [
    {
        _id: 'b1',
        name: 'بناء الثقة بالنفس وتطوير مهارات القيادة',
        category: 'جلسة',
        status: 'نشط',
        date: '2026-06-20',
        time: '10:00 - 11:30',
        participants: '8/15',
        rawParticipants: 8,
        capacity: 15,
        unitPrice: 0,
        totalPrice: 'مجاني',
    },
    {
        _id: 'b2',
        name: 'استراتيجيات التسويق الرقمي للمشاريع الصغيرة',
        category: 'جلسة',
        status: 'قيد الانتظار',
        date: '2026-06-25',
        time: '14:00 - 16:00',
        participants: '12/20',
        rawParticipants: 12,
        capacity: 20,
        unitPrice: 3500,
        totalPrice: 'دج 42,000',
    },
    {
        _id: 'b3',
        name: 'إطلاق مشروعك من الصفر: من الفكرة إلى الربح',
        category: 'جلسة',
        status: 'مكتمل',
        date: '2026-05-15',
        time: '09:00 - 12:00',
        participants: '15/15',
        rawParticipants: 15,
        capacity: 15,
        unitPrice: 8000,
        totalPrice: 'دج 120,000',
    },
    {
        _id: 'b4',
        name: 'تقنيات المقابلة الوظيفية واختيار الكفاءات',
        category: 'جلسة',
        status: 'ملغي',
        date: '2026-06-05',
        time: '11:00 - 12:45',
        participants: '3/10',
        rawParticipants: 3,
        capacity: 10,
        unitPrice: 5500,
        totalPrice: 'دج 16,500',
    },
    {
        _id: 'b5',
        name: 'أساسيات التفكير النقدي وحل المشكلات',
        category: 'برنامج',
        status: 'نشط',
        date: '2026-07-01',
        time: null,
        enrolledStudents: 10,
        capacity: 30,
        unitPrice: 0,
        totalPrice: 'مجاني',
    },
    {
        _id: 'b6',
        name: 'إتقان التسويق عبر مواقع التواصل الاجتماعي',
        category: 'برنامج',
        status: 'قيد الانتظار',
        date: '2026-07-10',
        time: null,
        enrolledStudents: 28,
        capacity: 30,
        unitPrice: 12000,
        totalPrice: 'دج 336,000',
    },
    {
        _id: 'b7',
        name: 'التخطيط المالي الشخصي والاستثمار الذكي',
        category: 'برنامج',
        status: 'مكتمل',
        date: '2026-06-08',
        time: null,
        enrolledStudents: 25,
        capacity: 25,
        unitPrice: 9500,
        totalPrice: 'دج 237,500',
    },
];

// ─── FAVORITES ────────────────────────────────────────────────────────────────
export const FAVORITES = [
    {
        id: 'f1',
        type: 'coach',
        title: 'كريم مساعدية',
        instructor: 'تسويق رقمي وريادة أعمال',
        rating: 4.9,
        price: null,
        image: null,
        avatarColor: 'from-amber-500 to-yellow-500',
    },
    {
        id: 'f2',
        type: 'session',
        title: 'بناء الثقة بالنفس وتطوير مهارات القيادة',
        instructor: 'أمينة بوعلام',
        rating: 4.9,
        price: 0,
        image: 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id: 'f3',
        type: 'course',
        title: 'إتقان التسويق عبر مواقع التواصل الاجتماعي',
        instructor: 'كريم مساعدية',
        rating: 4.7,
        price: 12000,
        image: 'https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id: 'f4',
        type: 'session',
        title: 'إطلاق مشروعك من الصفر: من الفكرة إلى الربح',
        instructor: 'كريم مساعدية',
        rating: 5.0,
        price: 8000,
        image: 'https://images.pexels.com/photos/1181396/pexels-photo-1181396.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id: 'f5',
        type: 'coach',
        title: 'سارة بن عمر',
        instructor: 'تخطيط مالي واستثمار',
        rating: 4.7,
        price: null,
        image: null,
        avatarColor: 'from-pink-600 to-rose-400',
    },
];

// ─── NOTIFICATIONS ────────────────────────────────────────────────────────────
export const NOTIFICATIONS = [
    {
        _id: 'n1',
        type: 'booking',
        title: 'تم تأكيد حجزك',
        message: 'تم تأكيد حجزك في جلسة "بناء الثقة بالنفس وتطوير مهارات القيادة" مع الكوتش أمينة بوعلام.',
        read: false,
        createdAt: '2026-06-13T18:30:00.000Z',
    },
    {
        _id: 'n2',
        type: 'payment',
        title: 'دفعة قيد الانتظار',
        message: 'لديك دفعة بقيمة 3500 DA قيد الانتظار لجلسة التسويق الرقمي.',
        read: false,
        createdAt: '2026-06-13T10:00:00.000Z',
    },
    {
        _id: 'n3',
        type: 'review',
        title: 'رد على تقييمك',
        message: 'قام الكوتش كريم مساعدية بالرد على تقييمك.',
        read: true,
        createdAt: '2026-06-10T15:45:00.000Z',
    },
    {
        _id: 'n4',
        type: 'program',
        title: 'دورة جديدة متاحة',
        message: 'تمت إضافة دورة جديدة "التخطيط المالي الشخصي والاستثمار الذكي" قد تهمك.',
        read: true,
        createdAt: '2026-06-08T09:00:00.000Z',
    },
    {
        _id: 'n5',
        type: 'reminder',
        title: 'تذكير بجلسة قادمة',
        message: 'لديك جلسة "استراتيجيات التسويق الرقمي للمشاريع الصغيرة" بعد يومين.',
        read: false,
        createdAt: '2026-06-12T07:00:00.000Z',
    },
];

// ─── PAYMENTS ─────────────────────────────────────────────────────────────────
export const PAYMENTS = [
    {
        _id: 'p1',
        description: 'دفع جلسة: إطلاق مشروعك من الصفر',
        amount: 8000,
        status: 'paid',
        method: 'baridimob',
        coachId: { _id: 'co1', fullName: 'كريم مساعدية' },
        createdAt: '2026-05-01T10:00:00.000Z',
        notes: '',
    },
    {
        _id: 'p2',
        description: 'دفع جلسة: استراتيجيات التسويق الرقمي',
        amount: 3500,
        status: 'pending',
        method: 'ccp',
        coachId: { _id: 'co1', fullName: 'كريم مساعدية' },
        createdAt: '2026-06-12T09:30:00.000Z',
        notes: '',
    },
    {
        _id: 'p3',
        description: 'دفع جلسة: تقنيات المقابلة الوظيفية',
        amount: 5500,
        status: 'refunded',
        method: 'transfer',
        coachId: { _id: 'co4', fullName: 'سارة بن عمر' },
        createdAt: '2026-05-28T12:00:00.000Z',
        notes: 'تم الاسترداد بسبب إلغاء الحجز.',
    },
    {
        _id: 'p4',
        description: 'دفع جلسة: بناء الثقة بالنفس',
        amount: 0,
        status: 'paid',
        method: 'cash',
        coachId: { _id: 'co2', fullName: 'أمينة بوعلام' },
        createdAt: '2026-06-10T08:00:00.000Z',
        notes: 'جلسة مجانية.',
    },
];

// ─── REVIEWS ──────────────────────────────────────────────────────────────────
export const REVIEWS = [
    {
        _id: 'r1',
        coachId: { _id: 'co1', fullName: 'كريم مساعدية' },
        sessionTitle: 'إطلاق مشروعك من الصفر: من الفكرة إلى الربح',
        rating: 5,
        comment: 'تجربة رائعة، الكوتش كان محترف جدا وأعطاني نصائح عملية ساعدتني فعلا في بدء مشروعي. أنصح بشدة بهذه الجلسة لكل من يفكر في ريادة الأعمال.',
        createdAt: '2026-05-16T12:00:00.000Z',
        coachReply: 'شكرا جزيلا على ثقتك، أتمنى لك التوفيق في مشروعك!',
    },
    {
        _id: 'r2',
        coachId: { _id: 'co2', fullName: 'أمينة بوعلام' },
        sessionTitle: 'بناء الثقة بالنفس وتطوير مهارات القيادة',
        rating: 4,
        comment: 'جلسة مفيدة جدا، تعلمت الكثير عن كيفية التعامل مع ضغط العمل.',
        createdAt: '2026-06-11T16:20:00.000Z',
        coachReply: null,
    },
];

// ─── COACH_PROFILE ────────────────────────────────────────────────────────────
// Utilisé par CoachProfile et CoachDashboard
export const COACH_PROFILE = {
    _id: 'co1',
    userId: 'u1',
    fullName: 'كريم مساعدية',
    artisticName: 'كريم كوتش',
    coachingName: 'كريم مساعدية',
    specialty: 'تسويق رقمي وريادة أعمال',
    location: 'الجزائر العاصمة',
    experience: 8,
    rating: 4.9,
    reviews: 234,
    isVerified: true,
    avatarColor: 'from-amber-500 to-yellow-500',
    email: 'karim.messaidia@fitora.dz',
    phoneNumber: '+213 555 123 456',
    bio: 'مدرب معتمد في مجال التسويق الرقمي وريادة الأعمال مع أكثر من 8 سنوات من الخبرة. ساعدت أكثر من 200 عميل في بناء علاماتهم التجارية وتطوير مشاريعهم.',
    website: 'https://karimcoach.dz',
    instagram: '@karim.coach.dz',
    facebook: 'karimcoach.dz',
    twitter: '@karimcoach',
    artTypes: ['تطوير الذات', 'ريادة الأعمال', 'التسويق والمبيعات'],
    services: ['جلسات كوتشينج فردية', 'جلسات جماعية', 'برامج تطوير مهني', 'استشارات مهنية'],
};

// ─── EARNINGS ─────────────────────────────────────────────────────────────────
// Utilisé par CoachEarnings et CoachDashboard
export const EARNINGS = {
    stats: {
        totalEarnings: 751500,
        thisMonth: 178000,
        commissionRates: {
            workshop: 15,   // % عمولة الجلسات
            course: 20,     // % عمولة البرامج
        },
    },
    monthly: [
        { month: 'جان', earnings: 95000  },
        { month: 'فيف', earnings: 112000 },
        { month: 'مار', earnings: 88500  },
        { month: 'أفر', earnings: 134000 },
        { month: 'ماي', earnings: 144000 },
        { month: 'جوان', earnings: 178000 },
    ],
    transactions: [
        {
            id: 't1',
            date: '2026-06-20',
            type: 'جلسة',
            item: 'بناء الثقة بالنفس وتطوير مهارات القيادة',
            customer: 'أحمد بن علي',
            amount: 0,
            commission: 0,
            net: 0,
            status: 'مكتمل',
        },
        {
            id: 't2',
            date: '2026-06-18',
            type: 'برنامج',
            item: 'إتقان التسويق عبر مواقع التواصل الاجتماعي',
            customer: 'سلمى خالدي',
            amount: 12000,
            commission: 2400,
            net: 9600,
            status: 'مكتمل',
        },
        {
            id: 't3',
            date: '2026-06-15',
            type: 'جلسة',
            item: 'استراتيجيات التسويق الرقمي للمشاريع الصغيرة',
            customer: 'يوسف مرابط',
            amount: 3500,
            commission: 525,
            net: 2975,
            status: 'مكتمل',
        },
        {
            id: 't4',
            date: '2026-06-12',
            type: 'برنامج',
            item: 'التخطيط المالي الشخصي والاستثمار الذكي',
            customer: 'نور بوزيد',
            amount: 9500,
            commission: 1900,
            net: 7600,
            status: 'مكتمل',
        },
        {
            id: 't5',
            date: '2026-06-10',
            type: 'جلسة',
            item: 'إطلاق مشروعك من الصفر: من الفكرة إلى الربح',
            customer: 'عمر تومي',
            amount: 8000,
            commission: 1200,
            net: 6800,
            status: 'مكتمل',
        },
        {
            id: 't6',
            date: '2026-06-05',
            type: 'جلسة',
            item: 'تقنيات المقابلة الوظيفية واختيار الكفاءات',
            customer: 'ليلى عيسى',
            amount: 5500,
            commission: 825,
            net: 4675,
            status: 'قيد الانتظار',
        },
        {
            id: 't7',
            date: '2026-05-28',
            type: 'برنامج',
            item: 'أساسيات التفكير النقدي وحل المشكلات',
            customer: 'رياض حمزة',
            amount: 0,
            commission: 0,
            net: 0,
            status: 'مكتمل',
        },
        {
            id: 't8',
            date: '2026-05-20',
            type: 'جلسة',
            item: 'استراتيجيات التسويق الرقمي للمشاريع الصغيرة',
            customer: 'إيمان بوشلاغم',
            amount: 3500,
            commission: 525,
            net: 2975,
            status: 'مكتمل',
        },
        {
            id: 't9',
            date: '2026-05-15',
            type: 'برنامج',
            item: 'إتقان التسويق عبر مواقع التواصل الاجتماعي',
            customer: 'كمال درار',
            amount: 12000,
            commission: 2400,
            net: 9600,
            status: 'مكتمل',
        },
        {
            id: 't10',
            date: '2026-05-10',
            type: 'جلسة',
            item: 'إطلاق مشروعك من الصفر: من الفكرة إلى الربح',
            customer: 'سارة منصور',
            amount: 8000,
            commission: 1200,
            net: 6800,
            status: 'مكتمل',
        },
    ],
};

// ─── COACH_COURSES ────────────────────────────────────────────────────────────
export const COACH_COURSES = [
    {
        _id: 'cc1',
        title: 'أساسيات التفكير النقدي وحل المشكلات',
        description: 'دورة شاملة تغطي أدوات التفكير النقدي وتقنيات حل المشكلات المعقدة في بيئة العمل.',
        category: 'تطوير ذاتي',
        level: 'مبتدئ',
        type: 'مجانية',
        price: 0,
        duration: '3 سا',
        hasCertificate: true,
        status: 'نشط',
        enrolledStudents: 10,
        confirmedStudents: 10,
        image: 'https://images.pexels.com/photos/1181396/pexels-photo-1181396.jpeg?auto=compress&cs=tinysrgb&w=600',
        finalExamTitle: 'الامتحان النهائي للتفكير النقدي',
        passMark: 70,
        finalExamQuestions: [
            { id: 'fq1', text: 'ما هو أول خطوة في حل المشكلة؟', answerType: 'mcq', options: ['تحديد المشكلة', 'إيجاد الحلول', 'التقييم', 'التنفيذ'], correct: 0 },
        ],
        modules: [
            {
                id: 'm1', title: 'مقدمة في التفكير النقدي',
                lessons: [
                    { id: 'l1', title: 'ما هو التفكير النقدي؟', duration: '20 د', content: 'مقدمة شاملة.', contents: [{ id: 'c1', type: 'فيديو', url: 'https://youtube.com', mode: 'url' }] },
                ],
                quiz: { title: 'اختبار الوحدة 1', questions: [{ id: 'q1', text: 'ما تعريف التفكير النقدي؟', answerType: 'mcq', options: ['التحليل الموضوعي', 'الحفظ', 'التقليد', 'الإبداع'], correct: 0 }] },
            },
        ],
    },
    {
        _id: 'cc2',
        title: 'إتقان التسويق عبر مواقع التواصل الاجتماعي',
        description: 'استراتيجيات متقدمة لبناء الحضور الرقمي وزيادة التفاعل على منصات التواصل الاجتماعي.',
        category: 'تسويق',
        level: 'متوسط',
        type: 'مدفوعة',
        price: 12000,
        duration: '8 سا',
        hasCertificate: true,
        status: 'نشط',
        enrolledStudents: 28,
        confirmedStudents: 25,
        image: 'https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg?auto=compress&cs=tinysrgb&w=600',
        finalExamTitle: 'الامتحان النهائي للتسويق الرقمي',
        passMark: 75,
        finalExamQuestions: [
            { id: 'fq1', text: 'ما أفضل منصة للتسويق B2B؟', answerType: 'mcq', options: ['LinkedIn', 'TikTok', 'Snapchat', 'Pinterest'], correct: 0 },
        ],
        modules: [
            {
                id: 'm1', title: 'استراتيجية المحتوى',
                lessons: [
                    { id: 'l1', title: 'أنواع المحتوى الرقمي', duration: '35 د', content: 'أنواع وأساليب المحتوى.', contents: [{ id: 'c1', type: 'فيديو', url: 'https://youtube.com', mode: 'url' }] },
                ],
                quiz: { title: 'اختبار استراتيجية المحتوى', questions: [{ id: 'q1', text: 'ما أهم عنصر في المحتوى؟', answerType: 'mcq', options: ['الجودة', 'الكمية', 'السرعة', 'التكلفة'], correct: 0 }] },
            },
        ],
    },
    {
        _id: 'cc3',
        title: 'التخطيط المالي الشخصي والاستثمار الذكي',
        description: 'تعلم كيف تدير ميزانيتك الشخصية وتستثمر أموالك بذكاء لتحقيق الاستقلال المالي.',
        category: 'مالية',
        level: 'مبتدئ',
        type: 'مدفوعة',
        price: 9500,
        duration: '5 سا',
        hasCertificate: true,
        status: 'نشط',
        enrolledStudents: 25,
        confirmedStudents: 25,
        image: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=600',
        finalExamTitle: 'الامتحان النهائي للتخطيط المالي',
        passMark: 60,
        finalExamQuestions: [
            { id: 'fq1', text: 'ما معنى التنويع في الاستثمار؟', answerType: 'mcq', options: ['توزيع المخاطر', 'تركيز الأموال', 'الإنفاق السريع', 'الادخار فقط'], correct: 0 },
        ],
        modules: [
            {
                id: 'm1', title: 'أساسيات الميزانية الشخصية',
                lessons: [
                    { id: 'l1', title: 'كيف تضع ميزانية شهرية', duration: '30 د', content: 'خطوات عملية للميزانية.', contents: [{ id: 'c1', type: 'PDF', url: 'https://example.com/budget.pdf', mode: 'url' }] },
                ],
                quiz: { title: 'اختبار الميزانية', questions: [{ id: 'q1', text: 'ما نسبة الادخار الموصى بها؟', answerType: 'mcq', options: ['20%', '5%', '50%', '1%'], correct: 0 }] },
            },
        ],
    },
];

// ─── USERS (admin) ────────────────────────────────────────────────────────────
export const USERS = [
    {
        id: 'co1',
        name: 'كريم مساعدية',
        email: 'karim.messaidia@fitora.dz',
        phone: '+213 555 123 456',
        type: 'COACH',
        status: 'نشط',
        joinDate: '2025-09-05T08:00:00.000Z',
        bookings: 0,
    },
    {
        id: 'co2',
        name: 'أمينة بوعلام',
        email: 'amina.boualam@fitora.dz',
        phone: '+213 661 234 567',
        type: 'COACH',
        status: 'نشط',
        joinDate: '2025-11-20T14:00:00.000Z',
        bookings: 0,
    },
    {
        id: 'co3',
        name: 'ياسين تيزي',
        email: 'yassine.tizi@fitora.dz',
        phone: '+213 770 345 678',
        type: 'COACH',
        status: 'معلق',
        joinDate: '2025-12-01T10:00:00.000Z',
        bookings: 0,
    },
    {
        id: 'co4',
        name: 'سارة بن عمر',
        email: 'sara.benomar@fitora.dz',
        phone: '+213 555 456 789',
        type: 'COACH',
        status: 'نشط',
        joinDate: '2025-10-15T08:00:00.000Z',
        bookings: 0,
    },
    {
        id: 'u1',
        name: 'أحمد بلقاسم',
        email: 'ahmed.belkacem@example.com',
        phone: '0555 123 456',
        type: 'CANDIDATE',
        status: 'نشط',
        joinDate: '2026-01-15T09:30:00.000Z',
        bookings: 5,
    },
    {
        id: 'u2',
        name: 'فاطمة زهراء',
        email: 'fatima.zahra@example.com',
        phone: '0770 345 678',
        type: 'CANDIDATE',
        status: 'معلق',
        joinDate: '2026-02-10T11:15:00.000Z',
        bookings: 2,
    },
    {
        id: 'u3',
        name: 'يوسف قادري',
        email: 'youssef.kadri@example.com',
        phone: '0661 567 890',
        type: 'CANDIDATE',
        status: 'نشط',
        joinDate: '2026-03-22T16:45:00.000Z',
        bookings: 8,
    },
    {
        id: 'u4',
        name: 'ليلى بوعلام',
        email: 'leila.boualam@example.com',
        phone: '0555 789 012',
        type: 'CANDIDATE',
        status: 'نشط',
        joinDate: '2026-04-08T13:20:00.000Z',
        bookings: 3,
    },
    {
        id: 'u5',
        name: 'عمر بن سالم',
        email: 'omar.bensalem@example.com',
        phone: '0661 890 123',
        type: 'CANDIDATE',
        status: 'نشط',
        joinDate: '2026-05-01T09:00:00.000Z',
        bookings: 1,
    },
];